Move the pow function, will add the test later.
NilFoundation/actor-math pull request #4
Opened 2023-06-05 12:34 UTC by martun

2023-06-06 14:08 UTC, Zerg1996 requested changes

2023-06-06 14:08 UTC, Zerg1996 commented on include/nil/actor/math/polynomial/polynomial_dfs.hpp
> +                    }
Don't really understand why it's so complex. 
As I understand - we just need to know new `this->size()` so we can skip fft to resize. 
So... why we just don't do something like this: 

new_degree = std::pow(current_degree, power);
new_size = crypto3::math::detail::power_of_two(std::max(new_degree, current_size))

2023-06-06 16:55 UTC, martun commented on include/nil/actor/math/polynomial/polynomial_dfs.hpp
> +                    }
Yes, I think you are right :) I don't know why I wrote it in such way. Changing in crypto3/math, then here.

2023-06-06 17:32 UTC, martun commented on include/nil/actor/math/polynomial/polynomial_dfs.hpp
> +                    }
Changed in crypto3-math

2023-06-07 10:14 UTC, Zerg1996 approved these changes

2023-06-07 11:32 UTC, merged